version: '3.8'

services:
  aircat-server-lite:
    image: upcyan/aircat-server-lite:latest
    container_name: aircat-server-lite
    ports:
      - "9000:9000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai